server:
  dev:
    enabled: true
  updateStrategyType: "RollingUpdate"
  ingress:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: "nginx"
    activeService: true
    hosts:
      - host: vault.aoneshop.in
        paths:
          - /
    tls:
     - secretName: vault-tls
       hosts:
         - vault.aoneshop.in

ui:
  enabled: true
  activeVaultPodOnly: true
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
  externalTrafficPolicy: Cluster


extraInitContainers:
  - name: oauthapp
    image: "alpine"
    command: [sh, -c]
    args:
      - cd /tmp &&
        wget https://github.com/puppetlabs/vault-plugin-secrets-oauthapp/releases/download/v1.2.0/vault-plugin-secrets-oauthapp-v1.2.0-linux-amd64.tar.xz -O oauthapp.xz &&
        tar -xf oauthapp.xz &&
        mv vault-plugin-secrets-oauthapp-v1.2.0-linux-amd64 /usr/local/libexec/vault/oauthapp &&
        chmod +x /usr/local/libexec/vault/oauthapp
    volumeMounts:
      - name: plugins
        mountPath: /usr/local/libexec/vault
